# Generated by Django 3.1.7 on 2021-03-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('content', models.CharField(max_length=100)),
                ('is_right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SudentAnswerModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snumber', models.CharField(max_length=6)),
                ('task_id', models.IntegerField()),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestFileModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='task/tests', verbose_name='Plik')),
                ('name', models.CharField(max_length=100, verbose_name='Wyświetlana nazwa testu')),
                ('has_been_chcecked', models.BooleanField(default=False)),
                ('date_start', models.DateTimeField(verbose_name='Data rozpoczęcia testu')),
                ('date_end', models.DateTimeField(verbose_name='Data zakończenia testu')),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_id', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
