# Generated by Django 3.1.7 on 2021-03-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20210303_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswerModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snumber', models.CharField(max_length=6)),
                ('task_id', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='SudentAnswerModel',
        ),
        migrations.RemoveField(
            model_name='questionanswermodel',
            name='task_id',
        ),
        migrations.AddField(
            model_name='questionanswermodel',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionanswermodel',
            name='test_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testquestionmodel',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testquestionmodel',
            name='test_id',
            field=models.IntegerField(default=0),
        ),
    ]
