# Generated by Django 3.1.7 on 2021-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20210304_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswermodel',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
