# Generated by Django 3.1.7 on 2021-03-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_studentpoitstest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentPoitsTest',
            new_name='StudentPointsTest',
        ),
    ]
