# Generated by Django 3.1.5 on 2021-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('who_answered', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('test', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('question_content', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answer', models.BooleanField(default=False)),
                ('asking_student', models.CharField(max_length=6)),
            ],
        ),
    ]
