# Generated by Django 3.1.5 on 2021-02-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default='null', max_length=1024),
        ),
    ]
