# Generated by Django 3.1.5 on 2021-02-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPromela',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('who_answered', models.CharField(max_length=30)),
                ('content', models.TextField(default='null', max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('test', models.CharField(max_length=10)),
                ('has_teacher_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPromela',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('question_content', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answer', models.BooleanField(default=False)),
                ('asking_student', models.CharField(max_length=6)),
            ],
        ),
    ]
