# Generated by Django 3.1.5 on 2021-02-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_answer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='has_teacher_answered',
            field=models.BooleanField(default=False),
        ),
    ]
