# Generated by Django 3.0.5 on 2021-03-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210302_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.TextField(default=None, max_length=256),
        ),
    ]
