# Generated by Django 3.0.5 on 2021-03-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210302_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-date',)},
        ),
    ]
