# Generated by Django 3.0.5 on 2021-03-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210302_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='has_teacher_answered',
            field=models.BooleanField(default=False),
        ),
    ]
