# Generated by Django 3.1.7 on 2021-03-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promela', '0009_auto_20210306_1253'),
        ('upload', '0026_auto_20210305_1728'),
        ('forum', '0006_answer_has_teacher_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPromela',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField()),
                ('who_answered', models.CharField(max_length=30)),
                ('content', models.TextField(default=None, max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerXML',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField()),
                ('who_answered', models.CharField(max_length=30)),
                ('content', models.TextField(default=None, max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPromela',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_content', models.TextField(default=None, max_length=1024, verbose_name='Zadaj pytanie')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answer', models.BooleanField(default=False)),
                ('asking_student', models.CharField(max_length=6)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Promela.teachertask')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='QuestionXML',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_content', models.TextField(default=None, max_length=1024, verbose_name='Zadaj pytanie')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answer', models.BooleanField(default=False)),
                ('asking_student', models.CharField(max_length=6)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.tasklist')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
