# Generated by Django 3.1.7 on 2021-03-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0028_auto_20210306_1655'),
        ('forum', '0007_auto_20210306_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10)),
                ('question_id', models.IntegerField()),
                ('who_answered', models.CharField(max_length=30)),
                ('content', models.TextField(default=None, max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10)),
                ('question_content', models.TextField(default=None, max_length=1024, verbose_name='Zadaj pytanie')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answer', models.BooleanField(default=False)),
                ('asking_student', models.CharField(max_length=6)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.tasklist')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='AnswerPromela',
        ),
        migrations.DeleteModel(
            name='AnswerXML',
        ),
        migrations.RemoveField(
            model_name='questionxml',
            name='task_id',
        ),
        migrations.DeleteModel(
            name='QuestionPromela',
        ),
        migrations.DeleteModel(
            name='QuestionXML',
        ),
    ]
