# Generated by Django 3.1.7 on 2021-03-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0028_auto_20210306_1655'),
        ('Promela', '0010_auto_20210306_1703'),
        ('forum', '0008_auto_20210306_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPromela',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_content', models.TextField(default=None, max_length=1024, verbose_name='Zadaj pytanie')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answer', models.BooleanField(default=False)),
                ('asking_student', models.CharField(max_length=6)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Promela.teachertask')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='QuestionXml',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_content', models.TextField(default=None, max_length=1024, verbose_name='Zadaj pytanie')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_teacher_answer', models.BooleanField(default=False)),
                ('asking_student', models.CharField(max_length=6)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.tasklist')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
