# Generated by Django 3.0.5 on 2021-03-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachertask',
            name='task_name',
            field=models.CharField(max_length=100),
        ),
    ]
