# Generated by Django 3.0.5 on 2021-03-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promela', '0002_auto_20210302_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttask',
            name='task_file',
            field=models.FileField(upload_to='task/promela/student_files', verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='teachertask',
            name='file',
            field=models.FileField(upload_to='task/promela/teacher_ltl', verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='teachertask',
            name='group_id',
            field=models.IntegerField(default=0, verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='teachertask',
            name='max_points',
            field=models.FloatField(default=0, verbose_name='Maksymalne punkty'),
        ),
        migrations.AlterField(
            model_name='teachertask',
            name='task_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nazwa zadania'),
        ),
    ]
