# Generated by Django 3.0.5 on 2021-03-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promela', '0004_studenttask_has_been_tested'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentOutput',
        ),
        migrations.AddField(
            model_name='studenttask',
            name='output_file',
            field=models.FileField(default=0, upload_to='', verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
