# Generated by Django 3.0.5 on 2021-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promela', '0006_auto_20210305_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachertask',
            name='max_points',
            field=models.IntegerField(default=0, verbose_name='Maksymalne punkty'),
        ),
    ]
