# Generated by Django 3.1.7 on 2021-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promela', '0007_auto_20210305_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='task_name',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
