# Generated by Django 3.1.7 on 2021-03-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promela', '0009_auto_20210306_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Promela.teachertask'),
        ),
    ]
