# Generated by Django 3.1.5 on 2021-01-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendedTasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskid', models.CharField(max_length=5)),
                ('snumber', models.CharField(max_length=6)),
                ('task', models.FileField(upload_to='task/sendedtasks/')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=100)),
                ('task', models.FileField(upload_to='task/tasklist/')),
            ],
        ),
    ]
