# Generated by Django 3.1.6 on 2021-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendedTasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskid', models.CharField(max_length=5)),
                ('snumber', models.CharField(max_length=6)),
                ('task', models.FileField(upload_to='task/sendedtasks/')),
                ('max_point', models.CharField(default=0, max_length=3)),
                ('point', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=100)),
                ('task', models.FileField(upload_to='task/tasklist/')),
            ],
        ),
    ]
