# Generated by Django 3.1.1 on 2020-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='checked',
            field=models.BooleanField(default='False'),
        ),
    ]
