# Generated by Django 3.1.1 on 2020-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_tasklist_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='checked',
        ),
        migrations.AddField(
            model_name='sendedtasks',
            name='checked',
            field=models.BooleanField(default='False'),
        ),
    ]
