# Generated by Django 3.1.6 on 2021-02-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20210218_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendedtasks',
            name='point',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
