# Generated by Django 3.1.5 on 2021-02-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20210218_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendedtasks',
            name='has_been_tested',
            field=models.BooleanField(default=False),
        ),
    ]
