# Generated by Django 3.1.5 on 2021-02-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200921_1853'),
        ('upload', '0004_auto_20200921_1908'),
    ]

    operations = [
    ]
