# Generated by Django 3.1.5 on 2021-02-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20210218_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plagiat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snumber1', models.CharField(max_length=6)),
                ('snumber2', models.CharField(max_length=6)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('plagiat', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='sendedtasks',
            name='has_been_tested',
            field=models.BooleanField(default=False),
        ),
    ]
