# Generated by Django 3.1.5 on 2021-02-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_sendedtasks_has_been_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendedtasks',
            name='group',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
