# Generated by Django 3.1.5 on 2021-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_sendedtasks_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plagiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snumber1', models.CharField(max_length=6)),
                ('snumber2', models.CharField(max_length=6)),
                ('task_id', models.CharField(max_length=5)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('plagiat', models.CharField(max_length=4)),
            ],
        ),
    ]
