# Generated by Django 3.1.5 on 2021-02-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_plagiat'),
        ('upload', '0005_auto_20210219_1212'),
    ]

    operations = [
    ]
