# Generated by Django 3.1.6 on 2021-02-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_merge_20210219_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
