# Generated by Django 3.1.5 on 2021-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_auto_20210219_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
