# Generated by Django 3.1.6 on 2021-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_auto_20210219_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promela',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskid', models.CharField(max_length=5)),
                ('snumber', models.CharField(max_length=6)),
                ('task', models.FileField(upload_to='task/Promela/Studentstask/')),
                ('output', models.FileField(upload_to='task/Promela/Studentoutput/')),
                ('has_been_tested', models.BooleanField(default=False)),
                ('group', models.CharField(default='0', max_length=10)),
                ('point', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskListPromela',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=100)),
                ('task', models.FileField(upload_to='task/PromelaList/')),
                ('max_points', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
