# Generated by Django 3.1.6 on 2021-02-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_promela_tasklistpromela'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promela2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskid', models.CharField(max_length=5)),
                ('snumber', models.CharField(max_length=6)),
                ('task', models.FileField(upload_to='task/Promela/Studentstask/')),
                ('output', models.FileField(upload_to='task/Promela/Studentoutput/')),
                ('group', models.CharField(default='0', max_length=10)),
                ('point', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='promela',
            name='output',
        ),
        migrations.RemoveField(
            model_name='promela',
            name='point',
        ),
        migrations.AddField(
            model_name='promela',
            name='taskcopy',
            field=models.FileField(default=0, upload_to='task/Promela/Studentstaskcopies/'),
        ),
    ]
