# Generated by Django 3.1.6 on 2021-02-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20210220_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promela',
            name='taskcopy',
            field=models.FileField(upload_to='task/Promela/Studentstaskcopies/'),
        ),
    ]
