# Generated by Django 3.1.7 on 2021-02-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_auto_20210220_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendedtasks',
            options={'ordering': ('-group',)},
        ),
    ]
