# Generated by Django 3.1.7 on 2021-02-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_auto_20210225_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promela',
            options={'ordering': ('group', 'taskid')},
        ),
        migrations.AlterModelOptions(
            name='promela2',
            options={'ordering': ('group', 'taskid')},
        ),
    ]
