# Generated by Django 3.1.7 on 2021-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_auto_20210225_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='taskname',
            field=models.CharField(default='Brak tytułu', max_length=200),
        ),
        migrations.AddField(
            model_name='tasklistpromela',
            name='taskname',
            field=models.CharField(default='Brak Tytułu', max_length=200),
        ),
    ]
