# Generated by Django 3.0.5 on 2021-03-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_auto_20210302_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='taskname',
            field=models.CharField(max_length=200),
        ),
    ]
