# Generated by Django 3.0.5 on 2021-03-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_auto_20210302_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsPoints',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snumber', models.CharField(max_length=6)),
                ('taskid', models.IntegerField()),
                ('number_task', models.CharField(max_length=3)),
                ('points', models.IntegerField()),
            ],
            options={
                'ordering': ('taskid', 'snumber'),
            },
        ),
        migrations.RemoveField(
            model_name='sendedtasks',
            name='point',
        ),
        migrations.AlterField(
            model_name='sendedtasks',
            name='max_point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sendedtasks',
            name='task',
            field=models.FileField(upload_to='task/sendedtasks/', verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='sendedtasks',
            name='taskid',
            field=models.CharField(max_length=5, verbose_name='Zadanie nr'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.FileField(upload_to='task/tasklist/', verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='taskname',
            field=models.CharField(default=None, max_length=200, verbose_name='Nazwa zadania'),
        ),
    ]
