# Generated by Django 3.0.5 on 2021-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0022_auto_20210304_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendedtasks',
            name='max_point',
            field=models.IntegerField(default=0),
        ),
    ]
