# Generated by Django 3.0.5 on 2021-03-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0023_auto_20210304_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspoints',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
