# Generated by Django 3.0.5 on 2021-03-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0024_auto_20210304_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspoints',
            name='taskid',
            field=models.CharField(max_length=3),
        ),
    ]
