# Generated by Django 3.1.7 on 2021-03-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210305_1728'),
        ('upload', '0026_auto_20210305_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='group_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
    ]
