# Generated by Django 3.0.5 on 2021-03-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0028_auto_20210306_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendedtasks',
            name='max_point',
        ),
    ]
