# Generated by Django 3.0.5 on 2021-03-06 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0029_plagiat_group_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plagiat',
            options={'ordering': ('-plagiat',)},
        ),
        migrations.AlterField(
            model_name='studentspoints',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.TaskList'),
        ),
    ]
