# Generated by Django 3.0.5 on 2021-03-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0030_auto_20210306_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendedtasks',
            name='max_point',
        ),
    ]
