# Generated by Django 3.0.5 on 2021-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0030_auto_20210306_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspoints',
            name='taskid',
            field=models.CharField(max_length=100),
        ),
    ]
