# Generated by Django 3.0.5 on 2021-03-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0031_auto_20210306_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspoints',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.TaskList'),
        ),
    ]
