# Generated by Django 3.1.5 on 2021-01-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='login',
            new_name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='last_username',
            field=models.DateTimeField(auto_now=True, verbose_name='last username'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
