# Generated by Django 3.1.5 on 2021-02-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210110_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='snumber',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Numer indeksu'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Login'),
        ),
    ]
