# Generated by Django 3.1.5 on 2021-02-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210218_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
    ]
