# Generated by Django 3.1.5 on 2021-02-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
    ]
