# Generated by Django 3.1.5 on 2021-02-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_groups_plagiaty_szablon_zadan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='groups',
        ),
        migrations.DeleteModel(
            name='Plagiaty',
        ),
        migrations.DeleteModel(
            name='Szablon_zadan',
        ),
    ]
